name: MyEnchants
version: '${project.version}'
main: com.github.cocomon3448.myenchants.MyEnchants
api-version: 1.18
authors: [ rammer3448 ]
description: nothing just custom enchants

commands:
  cheakenc:
    description: "Cheak enchantments of item in main hand"
  applyenc:
    description: "Applys custom enchantments to item in main hand"